debug: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    username: postgres
    password: dinara_02S
    # noinspection SpringBootApplicationYaml
#    driver-class-name: org.postgresql.Driver  # Corrected this line
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
